# Generated by Django 5.0 on 2024-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_team_abbrevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='stadium_location',
            field=models.URLField(null=True),
        ),
    ]
